FROM golang:1.19 AS build
WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o /usr/local/bin/app ./cmd/...

FROM alpine:3.19 AS certs
RUN apk add --no-cache tzdata ca-certificates && update-ca-certificates

FROM scratch
ENTRYPOINT ["/app"]
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=certs /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=build /usr/local/bin/app /app
